spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Giggle;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    intialization-mode: always


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB

spring.mvc.static-path-pattern: /static/**

logging:
  level:
    org.hibernate.SQL: debug