spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

spring.mvc.static-path-pattern: /static/**

logging:
  level:
    org.hibernate.SQL: debug